frx-challenges:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 1024m
      cert-manager.io/cluster-issuer: letsencrypt-prod
  pvc:
    storageClassName: premium-rwo
    storage: 10Gi

  evaluator:
    resources:
      requests:
        memory: 2Gi
        cpu: 0.5
      limits:
        memory: 4Gi
        cpu: 1
  dind:
    pvc:
      storageClassName: premium-rwo
    resources:
      # Guarantee 32G of RAM and 6 CPUs
      # this is where all our actual evaluations run
      requests:
        memory: 100Gi
        cpu: 10
      limits:
        memory: 100Gi
        cpu: 10

  adminUsers:
    - GeorgianaElena
    - yuvipanda
    - rhoadesScholar

  extraInitContainers:
    gcs-pull:
      name: gcs-pull
      image: google/cloud-sdk:497.0.0-stable
      command:
        - /bin/sh
        - -c
        # use printf so we don't interpret the \n in service account keys's private key
        # Delete empty directories, since `gcloud storage rsync` with `--delete-unmatched-destination-objects`
        # does not seem to actually delete directories created, only the leaf objects (sometimes).
        - |
          export CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE=/tmp/gcloud-auth && \
          printf '%s' "$SERVICE_ACCOUNT_JSON_KEY" > $CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE && \
          mkdir -p /opt/state/truth/ && \
          gcloud storage rsync --recursive --delete-unmatched-destination-objects \
            gs://cellmap-challenge-ground-truth-fake/ground_truth.zarr /opt/state/truth/ground_truth.zarr && \
          find /opt/state/truth/ -type d -empty -delete
      volumeMounts:
        - name: storage
          mountPath: /opt/state

  yamlSettings:
    overrides:
      # Make sure OAuth2 redirect URI is https, not http
      ACCOUNT_DEFAULT_HTTP_PROTOCOL: https
      # Image is built from https://github.com/janelia-cellmap/cellmap-segmentation-challenge
      EVALUATOR_DOCKER_IMAGE: quay.io/2i2c/cellmap-segmentation-challenge-evaluator:aea588ca952f
      EVALUATOR_DOCKER_CMD:
        - "csc"
        - "evaluate"
        - "--truth_path"
        - "/opt/ground_truth.zarr"
        - "--submission_path"
        - "{submission_path}"
        - "--result_file"
        - "{result_path}"
      EVALUATOR_DOCKER_EXTRA_BINDS:
        - /opt/state/truth/ground_truth.zarr:/opt/ground_truth.zarr:ro
      EVALUATOR_DOCKER_CONTAINER_CPU_LIMIT: 10
      # Set this to 100G now to see how much it actually gets to
      EVALUATOR_DOCKER_CONTAINER_MEMORY_LIMIT: 107374182400
      EVALUATOR_DOCKER_CONTAINER_ENV:
        # 4 knobs we have to tune the evaluator resource usage
        # and performance
        MAX_MAIN_THREADS: "4"
        MAX_LABEL_THREADS: "4"
        MAX_INSTANCE_THREADS: "2"
        # disable precompute limit
        PRECOMPUTE_LIMIT: 0
      EVALUATION_DISPLAY_CONFIG:
        - result_key: overall_semantic_score
          display_name: Semantic Score
          ordering: descending
          ordering_priority: 3
        - result_key: overall_instance_score
          display_name: Instance Score
          ordering: descending
          ordering_priority: 2
        - result_key: overall_score
          display_name: Score
          ordering: descending
          ordering_priority: 1
      SITE_LEADERBOARD_DESCRIPTION: >
        The leaderboard is sorted by the overall score of all test images, which accounts for the overall instance score and semantic score. The higher the overall score, the better the segmentation result.
      SITE_SUBMISSION_INSTRUCTIONS_MARKDOWN: |-
        We welcome your submission to the CellMap Segmentation Challenge! Before submitting, ensure all required fields are completed and that your algorithm outputs follow the guidelines in the [challenge documentation](https://janelia-cellmap.github.io/cellmap-segmentation-challenge/).

        Helpful Links:
        - [Submission Data Format](https://janelia-cellmap.github.io/cellmap-segmentation-challenge/submission_data_format.html) - Learn the required format for your submission files.
        - [Evaluation Criteria](https://janelia-cellmap.github.io/cellmap-segmentation-challenge/evaluation.html) - Understand how your submission will be assessed.
        - [Evaluation Resampling](https://janelia-cellmap.github.io/cellmap-segmentation-challenge/evaluation_resampling.html) - Details on how resampling is handled during evaluation.
        For any technical issues or questions, [reach out to our support team](mailto:cellmapchallenge@janelia.hhmi.org).
      SITE_SUBMISSION_TOC_LABEL: |-
        I agree to the Terms and Conditions as described below.

        **Terms and Conditions**

        The CellMap Segmentation Challenge offers you the opportunity to push the 
        boundaries of AI-driven biological image analysis by developing segmentation 
        models for a richly detailed collection of electron microscopy datasets.
        Participating in the CellMap Segmentation Challenge in any capacity requires 
        accessing and using the OpenOrganelle data repository (the “OpenOrganelle 
        Repository”) maintained by the Janelia Research Campus of the Howard Hughes 
        Medical Institute (“HHMI” or “we” or “us” or “our(s)”). By accessing or using the 
        OpenOrganelle Repository or any data and information made available on or 
        through the OpenOrganelle Repository, you agree to the [OpenOrganelle Terms of 
        Use](https://www.openorganelle.org/terms_of_use).

        Please read these CellMap Segmentation Challenge Terms of Participation 
        carefully. By competing in, and seeking to win, the CellMap Segmentation 
        Challenge, you agree to these CellMap Segmentation Challenge Terms of 
        Participation. If you do not agree to these CellMap Segmentation Challenge Terms 
        of Participation, you may not submit to us any visualization predictions or related 
        data and other information for a dataset obtained from the OpenOrganelle 
        Repository and you may not participate in the CellMap Segmentation Challenge.
        When you submit your visualization prediction(s) (“Predictions”) and related data, 
        including but not limited to metadata and other information (“Data”) for one or 
        more high-resolution electron microscopy datasets obtained from the 
        OpenOrganelle Repository by uploading them through the [CellMap Segmentation 
        Challenge online submission portal](https://cellmapchallenge.janelia.org/submissions/), you:

        - represent, warrant, and covenant that (a) you either own the Predictions 
        and the Data or have appropriate licenses or permissions necessary for the 
        Predictions and the Data to be made available to us; (b) the Predictions and 
        the Data do not, and the use thereof by us will not, infringe, misappropriate,
        or otherwise violate the intellectual property rights of any other person; and
        (c) the Predictions and the Data comply with all applicable laws, rules, and 
        regulations;
        - grant to HHMI and its contractors an irrevocable, non-exclusive, world-
        wide, royalty-free, sub-licensable, perpetual license (i) to all such 
        Predictions and Data under the terms of the CC BY 4.0 license; and (ii) to 
        use, store, make derivative works of, reproduce, publish, display and 
        distribute any and all such Predictions and Data, in all cases for HHMI's 
        internal research purposes; and
        - understand and agree that (A) you may be entered as a competitor in, and 
        potential winner of, the CellMap Segmentation Challenge; and (B) 
        information about you and the Predictions and Data you submit, including 
        but not limited to your name(s), your submission name(s), your GitHub 
        repository(ies), and your GitHub profile picture(s), may appear on and in the
        Cellmap Segmentation Challenge website(s) and related repository(ies) 
        (collectively, the “Cellmap Segmentation Challenge Sites”), including but 
        not limited to the leaderboard section thereof.

        *Note:* Upon completion of the CellMap Segmentation Challenge, we may be back 
        in contact to request permission to share the Prediction and the Data outside 
        HHMI.
      SITE_SUBMISSION_FORM_SCHEMA:
        type: object
        properties:
          name:
            type: "string"
            title: "Submission owner"
            helpText: "Your full name."
            format: "string"
          email:
            type: "string"
            title: "Email Address"
            format: "email"
          institution:
            type: "string"
            title: "Institution"
            format: "string"
          team:
            type: "string"
            title: "Team Name"
            helpText: "Choose a team name for your submission."
            required: true
            leaderboard_display: true
          open_source:
            type: "string"
            title: "Open source?"
            choices: ["Yes", "No"]
            format: "string"
            widget: "radio"
          repo:
            type: "string"
            title: "Repository"
            helpText: "If 'Yes' selected, link to public open source repository."
            format: "uri"
      SITE_NAME: CellMap Challenge
      SITE_LOGO_URL: header-logo
      SITE_PAGE_HEADER_IMAGE_URL: home-hero-image
      SITE_FOOTER_HTML: |-
        <style>
          footer, footer a {
            color: #838286;
            text-decoration: none
          }
        </style>
        <footer class="text-center break-bootstrap-container py-4 text-uppercase">
          <div class="container">
            <div class="d-flex flex-column gap-3">
              <div>
                <a href="https://www.janelia.org/project-team/cellmap">
                  <img src="/file/footer-logo-cellmap" height="48px" width="auto" />
                </a>
                <a href="https://www.janelia.org/">
                  <img
                    class="ms-2"
                    src="/file/footer-logo-hhmi"
                    height="48px"
                    width="auto"
                  />
                </a>
                <a href="https://2i2c.org/">
                  <img
                    class="ms-2"
                    src="/file/2i2c-blue-logo"
                    height="48px"
                    width="auto"
                  />
                </a>
              </div>
              <div>
                <small>
                  <p>
                    © 2024 CellMap Segmentation Challenge. <br />
                    This challenge is brought to you by the CellMap Project Team at
                    HHMI's Janelia Research Campus
                  </p>
                </small>
              </div>
              <div>
                <small>
                  <p>
                    <a href="mailto:cellmapchallenge@janelia.hhmi.org">Contact Us</a> |
                    <a href="https://openorganelle.janelia.org/">OpenOrganelle</a>
                  </p>
                </small>
              </div>
            </div>
          </div>
        </footer>
        <script defer data-domain="cellmapchallenge.janelia.org" src="https://plausible.io/js/script.js"></script>
